### ISSUE TITLE
Display certificate chain graphically

### ISSUE THREAD

**Issue by Mertsch** [dEajL3kA/certviewer#1]
Would be great if it was possible to see the dependency on parent certificates (in a graphical way).
And see if the path is invalid (missing, expired, ...) at some point.

Hope that is a suggestion you would consider :-)

Thanks for your work!

**Comment by dEajL3kA** [comment]
Hello. Thanks for your suggestion!

However, I think this is out of scope for this simple tool. This is a tool to display a _single_ given X.509 certificate. Building an entire certificate _chain_ would require access to a certificate store where we can find that _issuer's_ certificate and the corresponding _root_ certificate. It is unclear which certificate store should be used. Using the Windows certificate store might be an option, but won't work for certificates that are **not** from one of the approved "commercial" CA's that Windows has in its store. Or do we require that the uses passed the complete certificate chain in a single PEM file? Won't work with DER encoded certificates, though! Or, in some cases, it might be possible to download the _issuer's_ certificate (if the certificate has an AIA extension with the issuer CA download URL), but this is complicated, and we would have to do it recursively, if we also want to get the root certificate...

Regards.
